name: Build and Run

on:  
  push:
    branches: [ main ]
    
jobs:  
  build:    
    runs-on: [self-hosted, windows]
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Build Solution
        run: 
          dotnet build ResultFunctional.sln -c Release

      - name: Test Solution
        run: |
          dotnet test ResultFunctional.sln -c Release

      - name: NuGet push github
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ secrets.GithubApiKey }} --store-password-in-clear-text
          dotnet nuget push .\ResultFunctional\bin\Release\*.nupkg --skip-duplicate --no-symbols true --source github
          
      - name: NuGet push nuget.org
        run: | 
          dotnet nuget push .\ResultFunctional\bin\Release\*.nupkg  --api-key ${{ secrets.NugetApiKey }} --source https://api.nuget.org/v3/index.json