name: Build and Run

on:  
  push:
    branches: [ main ]
    
jobs:  
  build:    
    runs-on: [self-hosted, windows]
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Build Solution
        run: 
          dotnet build -c Release

      - name: Test Solution
        run: |
          dotnet test -c Release

      - name: NuGet push nuget.org
        run: | 
          dotnet nuget push .\ResultFunctional\bin\Release\*.nupkg  --api-key ${{ secrets.NugetApiKey }} --source https://api.nuget.org/v3/index.json